config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :contacts
  get 'dashboard', to: 'dashboard#index', as: :user_root
  
  post 'create_payid', to: 'dashboard#create_payid'
  post 'create_request', to: 'dashboard#create_request'

  devise_for :users
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'qr-scan', to: 'basic_qr_codes#index'
  get 'search', to: 'users#search'
  get 'requests', to: 'users#requests'
  get 'invoice', to: 'users#invoice'

  root to: 'pages#home'
  get 'home', to: 'pages#home'

  get 'profile', to: 'users#me'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def index
    @qr_code = current_user.qr_code_svg
    @qr_code_svg = @qr_code.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      standalone: true
    )
  end

  def create_request
    if params['amount'].present?
      r = Request.new
      r.sender = current_user
      r.amount = params[:amount]
      recipient = User.where(payid: params[:recipient]).first
      r.recipient = recipient
      r.save!
      redirect_to "/requests", notice: "Your request was successfully sent!"
    end
  end

  def create_payid
    username = params['username'] || current_user.email.split('@')[0] || "random#{rand(1000..9000)}"
    if params['username'].present?
      begin
        if params['xrp_address'].present?
          current_user.xrp_address = params['xrp_address']
          current_user.xrp_secret = params['xrp_seed']
          response = Unipay::Client.new.create_payid(params[:username], xrp_address: params['xrp_address'])

        else
          test_wallet = Payment::Client.new(current_user).test_wallets[2]
          current_user.xrp_address = test_wallet[:address]
          current_user.xrp_secret = test_wallet[:secret]
          response = Unipay::Client.new.create_payid(params[:username], xrp_address: current_user.xrp_address)
        end
        current_user.payid = response[:payid].split('@')[0]
        current_user.xrp_balance = 1000
        current_user.save!
        redirect_to dashboard_path, notice: "Your PayID was successfully created!"

      rescue Exception => e
        throw 'e' # show error message
      end
      
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_payment.html.erb
<div class="modal fade" id="makePaymentModal" tabindex="-1" role="dialog" aria-labelledby="makePaymentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="makePaymentModalLabel">Make Payment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
   
      <div class="container">
        <a href="qr-scan"><button class="btn btn-block btn-primary mt-5">Scan QR Code</button></a>
        <h5 class="pt-5 text-center"> Or</h5>

      </div>
      <div class="form-story">
        <%= form_for Contact.new, as: :contact, url: contacts_path, method: :post do |f| %>
        <div class="modal-body">
      
          <div class="mb-6">
            <div class="label">Enter Unipay ID</div>
            <%= f.text_field :payid, class: "form-control", required: true %>
          </div>

         <br>

         
    
      <div class="modal-footer">
        <div class="mb-6">
          <button class="btn-pay btn btn-lg btn-primary" type="submit">Proceed</button>
        </div>
      </div>
      <% end %>
          </div>
      </div>
    </div>
  </div>
</div>




<div class="modal fade" id="qrModal" tabindex="-1" role="dialog" aria-labelledby="qrModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="qrModalLabel">Make Payment to <%= current_user.payid_full %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
   
      <div class="container my-5  mx-5 qr-display">
        <%= svg = @qr_code.as_svg( offset: 0, color: "000", shape_rendering: 'crispEdges', module_size: 11, standalone: true ).html_safe %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<%- if !current_user.payid.present? %>
  <div class="container">
    <div class="py-5 text-center">
          <%= form_with(url: create_payid_path, method: :post) do %>

      <h2 class="pt-5">Get your Unipay ID now</h2>
      <p class="lead">Create your universal payment ID</p>
    </div>

    <div class="row justify-content-md-center">
          
      
      <% hidden_field_tag :username %>
      <div class="col-md-6 col-sm-12">
        <h4 class="mb-3">Pay ID</h4>
          <div class="row">


            <div class="mb-3">
              <%# <label for="username">Username</label> %>
              <div class="input-group">
                
                <%= text_field_tag(:username,'', class: 'form-control',  placeholder: 'Username', required: true ) %>
                <div class="input-group-prepend">
                  <span class="input-group-text">$insta-pay.net</span>
                </div>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>
          </div>


           

          <div class="row pt-3">
            <%# <div class="col-md-12"> %>
              <label for="country">Type</label>
              <select class="custom-select d-block w-100" id="country" required>
                <option value="">Choose...</option>
                <option>XRP</option>
                <option>BTC</option>
                <option>ETH</option>
                <option>Credit/Debit Cards</option>

              </select>
              <div class="invalid-feedback">
                Please select a valid country.
            </div>
            <div class="row py-3">
              <div class="col-md-12">
                <label for="cc-name">Wallet Address</label>
                <%= text_field_tag(:xrp_address,'', class: 'form-control',  placeholder: 'Wallet Address', required: false ) %>
                <%# <small class="text-muted">Wallet Address</small> %>
                <div class="invalid-feedback">
                 Wallet address is required
                </div>
              </div>
            </div>
            <div class="row py-3">
              <div class="col-md-12">
                <label for="cc-name">Seed</label>
                <%= text_field_tag(:xrp_secret,'', class: 'form-control',  placeholder: 'Wallet Seed', required: false ) %>
                <%# <small class="text-muted">Wallet Seed</small> %>
                <div class="invalid-feedback">
                 Wallet seed is required
                </div>
              </div>
            </div>
            </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="same-address">
            <label class="custom-control-label" for="same-address">Create a test XRP wallet</label>
          </div>
        
          <hr class="mb-4">
          <button class="btn btn-primary btn-lg btn-block" type="submit">Create</button>
                <% end %> 

      </div>
    </div>
<%- else %>
  <div class="container contact-container">

    <div class="row justify-content-md-center">
      <%= image_tag(current_user.avatar_url, class: "small-contact-image img-fluid rounded-circle") %>
      </div>
    <div class="row justify-content-md-center">

      <h2 class="pt-1"><%= current_user.payid_full %> </h2>
      </div>
    <div class="row justify-content-md-center">

      <div class="col-md-6">
        <button class="btn btn-primary btn-lg btn-block my-5" data-toggle="modal" data-target="#makePaymentModal">Make a Payment</button>
      </div>
      <div class="col-md-6">
        <button class="btn btn-primary btn-lg btn-block my-5" data-toggle="modal" data-target="#qrModal">Receive Payment</button>

      </div>
    </div>
     <h4>Contacts</h4>
    <div class="row">
      <%- Contact.where(kind: :user, user: current_user).each do |contact| %>
        <a href="<%=contact_path(contact) %>" data-toggle="tootltio" title="<%= contact.name %> "><%= image_tag(contact.avatar_url, class: 'img-thumbnail avatar') %></a>
      <% end %>
    </div>

    <h4 class="py-5">Businesses</h4>
    <div class="row">
      <%- Contact.where(kind: :business).each do |contact| %>
        <a href="<%=contact_path(contact) %>" data-toggle="tootltio" title="<%= contact.name %> "><%= image_tag(contact.avatar_url, class: 'img-thumbnail avatar') %></a>
      <% end %>
    </div>

    <h4 class="py-5">Subscriptions</h4>
    <div class="row">
      <%- Contact.where(kind: 3).each do |contact| %>
        <a href="<%=contact_path(contact) %>" data-toggle="tootltio" title="<%= contact.name %> "><%= image_tag(contact.avatar_url, class: 'img-thumbnail avatar') %></a>
      <% end %>
    </div>
    <h4 class="py-5">Charities looking for donations</h4>
    <div class="row">
      <div class="row">
      <%- Contact.where(kind: :charity).each do |contact| %>
        <a href="<%=contact_path(contact) %>" data-toggle="tootltio" title="<%= contact.name %> "><%= image_tag(contact.avatar_url, class: 'img-thumbnail avatar') %></a>
      <% end %>
    </div>
    </div>
  </div>
<% end %>
<%= render 'payment' %>