config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :contacts
  get 'dashboard', to: 'dashboard#index', as: :user_root
  
  post 'create_payid', to: 'dashboard#create_payid'
  post 'create_request', to: 'dashboard#create_request'

  devise_for :users
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'qr-scan', to: 'basic_qr_codes#index'
  get 'search', to: 'users#search'
  get 'requests', to: 'users#requests'
  get 'invoice', to: 'users#invoice'

  root to: 'pages#home'
  get 'home', to: 'pages#home'

  get 'profile', to: 'users#me'

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :payid, presence: true
  enum kind: { user: 0, business: 1, charity: 2, subscriptions: 3 }
  # before_save :add_gravatar
  before_validation :add_name

  has_many :transactions, dependent: :destroy

  def payid_full
    "#{payid}@unipay"
  end

  def avatar_url
    avatar || 'avatar.png'
  end

  def add_gravatar
    if !avatar.present?
      email = self.email.downcase
      email_hash = Digest::MD5.hexdigest(email)
      self.avatar = "https://www.gravatar.com/avatar/#{email_hash}/?d=identicon"
    end
  end

  def add_name
    if !name.present?
      self.name = payid.capitalize
    end
  end

  def exchange_rate
    result = Cryptocompare::Price.find('USD', ['XRP','BTC', 'ETH'])
    result['USD']
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  layout 'dashboard'
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    payid = contact_params[:payid].split('@')[0]
    name = payid
    @contact = Contact.new(payid:  payid, name: name)
    @contact.user = current_user
    @contact.kind = :user

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:user_id, :name, :description, :payid, :type, :avatar)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :payid %>
    <%= form.text_field :payid %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Description</th>
      <th>Payid</th>
      <th>Type</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.user_id %></td>
        <td><%= contact.name %></td>
        <td><%= contact.description %></td>
        <td><%= contact.payid %></td>
        <td><%= contact.type %></td>
        <td><%= contact.avatar %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
   <script>
        window.onload = function () {
            let checkout = new RapydCheckoutToolkit({
                pay_button_text: "Click to pay",
                pay_button_color: "blue",
                id: "<%= flash[:checkout_id] %>",
            });
            checkout.displayCheckout();
        }
        window.addEventListener('onCheckoutPaymentSuccess', function (event) {
            console.log(event.detail)
        });
        window.addEventListener('onCheckoutFailure', function (event) {
            console.log(event.detail.error)
        });

    
    </script>
<%#   
  <div class="modal fade show" id="makeCheckoutModal" tabindex="-1" role="dialog" aria-labelledby="makeCheckoutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="makeCheckoutModalLabel">Make Payment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
   
      
      
    </div>
  </div>
</div> %>
<div class="container">
        <div style="width: 500px" id="rapyd-checkout"></div>
      </div>


  <div class="container">

    <div class="py-5 text-center">
     <%= image_tag(@contact.avatar_url, class: "contact-image img-fluid rounded-circle") %>
      <h2 class="pt-5"><%= @contact.payid_full %> </h2>
      <p class="lead"><%= @contact.name %></p>
    </div>

     <div class="row justify-content-md-center">
     <div class="col-md-6 col-sm-12">
        <%= form_for Transaction.new, as: :transaction, url: transactions_path, method: :post do |f| %>
      <div class="form-story">
          <div class="modal-body">
            <div class="mb-6">
              <div class="label">Unipay ID</div>
            <%= f.text_field :payid, class: "form-control", required: true, value: @contact.payid_full %>

            </div>

          

            <div class="mb-3 py-3 maps-autocomplete">
              <div class="label">Amount ($)</div>
            <%= f.text_field :from_value, class: "form-control", required: true %>
              
            </div>

           
          <div class="col-md-12">
        <button class="btn btn-primary btn-lg btn-block btn-payment my-5" >Make a Payment</button>
      </div>
        <%# <button class="btn btn-primary btn-lg btn-block btn-payment my-5" type="submit">Make a Payment</button> %>
              
          </div>
          </div>
          <% end %>
      <h5 class="">Raise a invoice</h5>
      <div class="row justify-content-md-center">
      <div class="col-md-11">
        <button class="btn btn-primary btn-lg btn-block btn-payment my-5" data-toggle="modal" data-target="#invoiceModal">Request Payment</button>
      </div>
      </div>

  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Recent Transactions</h6>
      <%- @contact.transactions.each do |transaction| %>

      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= transaction.user.payid_full %></strong>
          <%= "You sent #{transaction.from_value} #{transaction.from_currency} #{time_ago_in_words(transaction.created_at)} ago" %>
        </p>
        </div>
      <% end %>
    <small class="d-block text-right mt-3">
      <a href="#">All updates</a>
    </small>
  </div>
  
</div>
</div>
</div>


<div class="modal fade" id="invoiceModal" tabindex="-1" role="dialog" aria-labelledby="invoiceModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="invoiceModalLabel">Request payment from <%= @contact.payid_full %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
   
      <div class="container col-md-9  my-5  mx-5">
      <%= form_with(url: create_request_path, method: :post)  do  %>
              <%= text_field_tag(:amount,'', class: 'form-control',  placeholder: 'Amount', required: true ) %>
            <%= hidden_field_tag :recipient,  @contact.payid %>
              
            <button class="btn btn-primary btn-lg btn-block btn-payment my-5" type="submit">Request</button>
        <% end %>
    </div>
  </div>
</div>