config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :contacts
  get 'dashboard', to: 'dashboard#index', as: :user_root
  
  post 'create_payid', to: 'dashboard#create_payid'
  post 'create_request', to: 'dashboard#create_request'

  devise_for :users
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'qr-scan', to: 'basic_qr_codes#index'
  get 'search', to: 'users#search'
  get 'requests', to: 'users#requests'
  get 'invoice', to: 'users#invoice'

  root to: 'pages#home'
  get 'home', to: 'pages#home'

  get 'profile', to: 'users#me'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end


  # POST /transactions
  # POST /transactions.json
  def create
    if params['transaction']['contact'].present?
       redirect_to dashboard_path, notice: "You request for payment was successfully sent"
       return
    end
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user
    contact = Contact.find_by_payid(params['transaction']['payid'].split('@')[0])
    @transaction.contact = contact
    @transaction.from_currency = 'USD'
    @transaction.to_currency = 'XRP'
    exchange_rate = Cryptocompare::Price.find('USD', 'XRP')
    @transaction.to_value = exchange_rate['USD']['XRP']

    client = Rapyd::Client.new
    @checkout_id = client.create_checkout_page(@transaction.from_value, @transaction.to_currency)
    respond_to do |format|
      if @transaction.save
        # flash[:checkout_id] = @checkout_id 
        format.html { redirect_to @transaction.contact, flash: { checkout_id: @checkout_id } }
        # format.html { render partial: 'checkout_modal' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:user, :contact, :from_value, :from_currency, :to_value, :to_currency)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_checkout_modal.html.erb
  
  <div class="modal fade show" id="makeCheckoutModal" tabindex="-1" role="dialog" aria-labelledby="makeCheckoutModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="makeCheckoutModalLabel">Make Payment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
   
      
      <div class="container">
        <div style="width: 500px" id="rapyd-checkout"></div>
      </div>
    </div>
  </div>
</div>



   <script>
        window.onload = function () {
            let checkout = new RapydCheckoutToolkit({
                pay_button_text: "Click to pay",
                pay_button_color: "blue",
                id: "checkout_c0f4b91a07cf35a4798b6e396ccd2490"
            });
            checkout.displayCheckout();
        }
        window.addEventListener('onCheckoutPaymentSuccess', function (event) {
            console.log(event.detail)
        });
        window.addEventListener('onCheckoutFailure', function (event) {
            console.log(event.detail.error)
        });

        // window.onload = function () {
        //   document.getElementById("makeCheckoutModal").modal('show');
        // }
    </script>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :from_value %>
    <%= form.text_field :from_value %>
  </div>

  <div class="field">
    <%= form.label :from_currency %>
    <%= form.text_field :from_currency %>
  </div>

  <div class="field">
    <%= form.label :to_value %>
    <%= form.text_field :to_value %>
  </div>

  <div class="field">
    <%= form.label :to_currency %>
    <%= form.text_field :to_currency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Contact</th>
      <th>From value</th>
      <th>From currency</th>
      <th>To value</th>
      <th>To currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.user %></td>
        <td><%= transaction.contact %></td>
        <td><%= transaction.from_value %></td>
        <td><%= transaction.from_currency %></td>
        <td><%= transaction.to_value %></td>
        <td><%= transaction.to_currency %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @transaction.user %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @transaction.contact %>
</p>

<p>
  <strong>From value:</strong>
  <%= @transaction.from_value %>
</p>

<p>
  <strong>From currency:</strong>
  <%= @transaction.from_currency %>
</p>

<p>
  <strong>To value:</strong>
  <%= @transaction.to_value %>
</p>

<p>
  <strong>To currency:</strong>
  <%= @transaction.to_currency %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>